[package]
name = "graph"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.26", features = ["derive"] }
colored = "3.0.0"
derive_more = { version = "1.0.0", features = ["display"] }
minifb = "0.27.0"
plotters = "0.3.7"
rand = "0.8.5"
serialport = "4.6.0"
